[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
    let g:neocomplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/rc/plugins/neosnippet.rc.vim'


[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_source = 'source ~/.vim/rc/plugins/unite.rc.vim'
hook_add = '''
    " インサート／ノーマルどちらからでも呼び出せるようにキーマップ
    nnoremap <silent> <C-u><C-u>
        \ :<C-u>Unite -buffer-name=files buffer file_mru file file/new<CR>
    inoremap <silent> <C-u><C-u>
        \ <ESC>:<C-u>Unite -buffer-name=files buffer file_mru file file/new<CR>
    nnoremap <silent> <C-u><C-f>
        \ :<C-u>UniteWithBufferDir -buffer-name=files buffer file_mru file file/new<CR>
    inoremap <silent> <C-u><C-f>
        \ <ESC>:<C-u>UniteWithBufferDir -buffer-name=files buffer file_mru file file/new<CR>
    " unite-outline用の設定
    nnoremap <silent> <C-u><C-o>
        \ :<C-u>Unite outline -no-start-insert -resume<CR>
    inoremap <silent> <C-u><C-o>
        \ <ESC>:<C-u>Unite outline -no-start-insert -resume<CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = [['n', '<Plug>']]
on_if = "isdirectory(bufname('%'))"
hook_source = 'source ~/.vim/rc/plugins/vimfiler.rc.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
